  // firstName: '',
  //     lastName: '',
  //     phone: '',
  //     location: '',
  //     company: '',
  //     field: '',
  //     tagline: '',
  //     username: '',
  //     password: '',
  //     profileImageUrl: '',


  //acceptedConnections
exports.acceptedConnections = [
  {firstName: 'Jim',
      lastName: 'Jones',
      phone: '2125463434',
      location: 'NYC',
      company: 'Lehman Brothers',
      field: 'finance',
      tagline: 'help me find a job',
      username: 'jim',
      password: 'jones',
      profileImageUrl: 'http://facts.be/app/uploads/David-Hasselhoff-face.jpg'},

  {firstName: 'John',
      lastName: 'Smith',
      phone: '3125463434',
      location: 'Jamestown',
      company: 'Virginia Co.',
      field: 'tea',
      tagline: 'need a new boss',
      username: 'John',
      password: 'Smith',
      profileImageUrl: 'https://www.biography.com/.image/c_fill,cs_srgb,dpr_1.0,g_face,h_300,q_80,w_300/MTIwNjA4NjMzOTc0MTk1NzI0/john-smith-9486928-1-402.jpg'},
]

exports.suggestedConnections =[
 {firstName: 'Tim',
      lastName: 'Taylor',
      phone: '6165463434',
      location: 'SF',
      company: 'Home Improvement',
      field: 'tools',
      tagline: 'help me find a job',
      username: 'Tim',
      password: 'Taylor',
      profileImageUrl: 'http://www.sonic1029.com/wp-content/blogs.dir/3/files/TIMTAYLOR.png'},

  {firstName: 'George',
      lastName: 'Foreman',
      phone: '9415463434',
      location: 'Reno',
      company: 'George Foreman',
      field: 'kitchenware',
      tagline: 'want to start boxing again',
      username: 'George',
      password: 'Foreman',
      profileImageUrl: 'http://cdn.images.express.co.uk/img/dynamic/130/590x/George-Foreman-525485.jpg'},

       {firstName: 'Alex',
      lastName: 'Trebek',
      phone: '5155463434',
      location: 'Hollywood',
      company: 'MGM',
      field: 'entertainment',
      tagline: 'daily doubler',
      username: 'Alex',
      password: 'Trebek',
      profileImageUrl: 'http://vignette3.wikia.nocookie.net/gameshows/images/0/0e/Alex-trebek-mustache.jpg/revision/latest?cb=20140102041845'},

  {firstName: 'Michael',
      lastName: 'James',
      phone: '6465463434',
      location: 'Boise',
      company: 'NPM',
      field: 'software',
      tagline: 'fun computers',
      username: 'Michael',
      password: 'James',
      profileImageUrl: 'https://pbs.twimg.com/profile_images/761986102676729856/R_hXAukf.jpg'},

]

exports.pendingConnectionsIncoming = [
 {firstName: 'Mick',
      lastName: 'Jagger',
      phone: '0105463434',
      location: 'UK',
      company: 'Rolling Stones',
      field: 'entertainment',
      tagline: 'this is cool',
      username: 'Mick',
      password: 'Jagger',
      profileImageUrl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTMxMTY4NTQ5N15BMl5BanBnXkFtZTcwMTY0NDk4Mw@@._V1_UY317_CR13,0,214,317_AL_.jpg'},

  {firstName: 'Tony',
      lastName: 'Montana',
      phone: '4345463434',
      location: 'Miami',
      company: 'Tony Montana Inc',
      field: 'coffee imports',
      tagline: 'the world is mine',
      username: 'Tony',
      password: 'Montana',
      profileImageUrl: 'http://vignette1.wikia.nocookie.net/scarface/images/4/44/Tony_Montana.jpg/revision/latest?cb=20120604034628&path-prefix=en'},

       {firstName: 'Jane',
      lastName: 'Austen',
      phone: '3335463434',
      location: 'Hampshire',
      company: ' Austen Book Co.',
      field: 'author',
      tagline: 'Emma Pride and Prejudice',
      username: 'Jane',
      password: 'Austen',
      profileImageUrl: 'http://www.daniel-bearman.com/wp-content/uploads/2015/04/Jane-Austen-7fd22ed7446999a4097e310067a85dea9ee15e04.jpg'},

  {firstName: 'Rick',
      lastName: 'Astley',
      phone: '6345463434',
      location: 'London',
      company: 'unemployed',
      field: 'entertainment',
      tagline: 'never gonna give you up',
      username: 'Rick',
      password: 'Astley',
      profileImageUrl: 'http://i234.photobucket.com/albums/ee136/suwarnaadi/hair/rick-astley-80s-hairstyle.jpg'}]


exports.pendingConnectionsOutgoing = [
      {firstName: 'Jim',
      lastName: 'Snow',
      phone: '3335463434',
      location: 'Maplewood',
      company: 'New York Times',
      field: 'journalism',
      tagline: 'i like to write',
      username: 'Jim',
      password: 'Snow',
      profileImageUrl: 'http://images.performgroup.com/di/library/omnisport/70/f5/derek-jeter-020215-getty-ftr-usjpg_1gub1gvmuyw0e1tpizje7sss8m.jpg?t=1432320339'},

  {firstName: 'Samuel',
      lastName: 'Wylie',
      phone: '2225463434',
      location: 'Birmingham',
      company: 'Shoes Inc.',
      field: 'shoemaker',
      tagline: 'buy these shoes',
      username: 'Samuel',
      password: 'Wylie',
      profileImageUrl: 'https://s-media-cache-ak0.pinimg.com/originals/fb/a7/26/fba726bdf868ecf85a49d40aa7e9f2d0.jpg'},

       {firstName: 'Van',
      lastName: 'Morrison',
      phone: '9995463434',
      location: 'Dublin',
      company: 'Van Morrison Band',
      field: 'singer',
      tagline: 'sha la la la la la ti da',
      username: 'Van',
      password: 'Morrison',
      profileImageUrl: 'http://www.wavelengthltd.co.uk/wp-content/uploads/2015/08/van-morrison-pic.jpg'},

  {firstName: 'Jack',
      lastName: 'Daniels',
      phone: '7775463434',
      location: 'Lynchburg',
      company: 'JD Distilling',
      field: 'spirits',
      tagline: 'your best friend',
      username: 'Jack',
      password: 'Daniels',
      profileImageUrl: 'https://s3-us-west-2.amazonaws.com/find-a-grave-prod/photos/2009/248/1556_125221940406.jpg'}]



