  // firstName: '',
  //     lastName: '',
  //     phone: '',
  //     location: '',
  //     company: '',
  //     field: '',
  //     tagline: '',
  //     username: '',
  //     password: '',
  //     profileImageUrl: '',


  //acceptedConnections
exports.acceptedConnections = [
  {firstName: 'Jim',
      lastName: 'Jones',
      phone: '2125463434',
      location: 'NYC',
      company: 'Lehman Brothers',
      field: 'finance',
      tagline: 'help me find a job',
      username: 'jim',
      password: 'jones',
      profileImageUrl: ''},

  {firstName: 'John',
      lastName: 'Smith',
      phone: '3125463434',
      location: 'Jamestown',
      company: 'Virginia Co.',
      field: 'tea',
      tagline: 'need a new boss',
      username: 'John',
      password: 'Smith',
      profileImageUrl: ''},
]

exports.suggestedConnections =[
 {firstName: 'Tim',
      lastName: 'Taylor',
      phone: '6165463434',
      location: 'SF',
      company: 'Home Improvement',
      field: 'tools',
      tagline: 'help me find a job',
      username: 'Tim',
      password: 'Taylor',
      profileImageUrl: ''},

  {firstName: 'George',
      lastName: 'Foreman',
      phone: '9415463434',
      location: 'Reno',
      company: 'George Foreman',
      field: 'kitchenware',
      tagline: 'want to start boxing again',
      username: 'George',
      password: 'Foreman',
      profileImageUrl: ''},

       {firstName: 'Alex',
      lastName: 'Trebek',
      phone: '5155463434',
      location: 'Hollywood',
      company: 'MGM',
      field: 'entertainment',
      tagline: 'daily doubler',
      username: 'Alex',
      password: 'Trebek',
      profileImageUrl: ''},

  {firstName: 'Michael',
      lastName: 'James',
      phone: '6465463434',
      location: 'Boise',
      company: 'NPM',
      field: 'software',
      tagline: 'fun computers',
      username: 'Michael',
      password: 'James',
      profileImageUrl: ''},

]

exports.pendingConnectionsIncoming = [
 {firstName: 'Mick',
      lastName: 'Jagger',
      phone: '0105463434',
      location: 'UK',
      company: 'Rolling Stones',
      field: 'entertainment',
      tagline: 'this is cool',
      username: 'Mick',
      password: 'Jagger',
      profileImageUrl: ''},

  {firstName: 'Tony',
      lastName: 'Montana',
      phone: '4345463434',
      location: 'Miami',
      company: 'Tony Montana Inc',
      field: 'coffee imports',
      tagline: 'the world is mine',
      username: 'Tony',
      password: 'Montana',
      profileImageUrl: ''},

       {firstName: 'Jane',
      lastName: 'Austen',
      phone: '3335463434',
      location: 'Hampshire',
      company: ' Austen Book Co.',
      field: 'author',
      tagline: 'Emma Pride and Prejudice',
      username: 'Jane',
      password: 'Austen',
      profileImageUrl: ''},

  {firstName: 'Rick',
      lastName: 'Astley',
      phone: '6345463434',
      location: 'London',
      company: 'unemployed',
      field: 'entertainment',
      tagline: 'never gonna give you up',
      username: 'Rick',
      password: 'Astley',
      profileImageUrl: ''}]


exports.pendingConnectionsOutgoing = [
      {firstName: 'Jim',
      lastName: 'Snow',
      phone: '3335463434',
      location: 'Maplewood',
      company: 'New York Times',
      field: 'journalism',
      tagline: 'i like to write',
      username: 'Jim',
      password: 'Snow',
      profileImageUrl: ''},

  {firstName: 'Samuel',
      lastName: 'Wylie',
      phone: '2225463434',
      location: 'Birmingham',
      company: 'Shoes Inc.',
      field: 'shoemaker',
      tagline: 'buy these shoes',
      username: 'Samuel',
      password: 'Wylie',
      profileImageUrl: ''},

       {firstName: 'Van',
      lastName: 'Morrison',
      phone: '9995463434',
      location: 'Dublin',
      company: 'Van Morrison Band',
      field: 'singer',
      tagline: 'sha la la la la la ti da',
      username: 'Van',
      password: 'Morrison',
      profileImageUrl: ''},

  {firstName: 'Jack',
      lastName: 'Daniels',
      phone: '7775463434',
      location: 'Lynchburg',
      company: 'JD Distilling',
      field: 'spirits',
      tagline: 'your best friend',
      username: 'Jack',
      password: 'Daniels',
      profileImageUrl: ''}]



